{{- if or .Values.backend.enabled .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chat-bot.fullname" . }}-secret
  labels:
    {{- include "todo-chat-bot.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded values
  db-password: {{ .Values.postgres.env.POSTGRES_PASSWORD | b64enc | quote }}
  {{- if .Values.backend.env.OPENAI_API_KEY }}
  openai-api-key: {{ .Values.backend.env.OPENAI_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.env.MCP_API_KEY }}
  mcp-api-key: {{ .Values.backend.env.MCP_API_KEY | b64enc | quote }}
  {{- end }}
{{- end }}