# OpenAPI Contract: AI Agent Chat API

## Overview
This document defines the API contract for the AI-powered chat endpoint that enables natural language task management through the OpenAI Agent system.

```yaml
openapi: 3.0.3
info:
  title: AI Agent Chat API
  description: API for interacting with the AI agent for task management
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production server
  - url: https://staging-api.example.com
    description: Staging server

paths:
  /api/{user_id}/chat:
    post:
      summary: Send a message to the AI agent
      description: Sends a user message to the AI agent and receives a response. Maintains conversation context.
      operationId: sendMessageToAgent
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user sending the message
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the AI agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request due to invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message to the AI agent
          example: "Add a task to buy groceries"
        conversation_id:
          type: string
          format: uuid
          description: Optional ID of an existing conversation to continue
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        metadata:
          type: object
          description: Additional metadata to attach to the message
          example:
            source: "mobile_app"
            timezone: "America/Los_Angeles"

    ChatResponse:
      type: object
      required:
        - conversation_id
        - message
        - timestamp
      properties:
        conversation_id:
          type: string
          format: uuid
          description: The ID of the conversation
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        message:
          $ref: '#/components/schemas/MessageContent'
        timestamp:
          type: string
          format: date-time
          description: When the response was generated
          example: "2023-10-01T12:00:00Z"
        next_action:
          type: string
          enum: [continue, wait_for_confirmation, completed]
          description: Suggested next action for the frontend
          example: "continue"

    MessageContent:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: [user, assistant, tool]
          description: The role of the message sender
          example: "assistant"
        content:
          type: string
          description: The content of the message
          example: "I've added 'buy groceries' to your task list."
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCall'
          description: Any tool calls made by the assistant

    ToolCall:
      type: object
      required:
        - id
        - function
      properties:
        id:
          type: string
          description: Unique identifier for the tool call
          example: "call_abc123"
        function:
          $ref: '#/components/schemas/FunctionCall'

    FunctionCall:
      type: object
      required:
        - name
        - arguments
      properties:
        name:
          type: string
          description: The name of the function to call
          example: "create_task"
        arguments:
          type: string
          description: JSON string of arguments for the function
          example: "{\"title\": \"buy groceries\", \"description\": \"Get milk, bread, and eggs\"}"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INVALID_INPUT"
        message:
          type: string
          description: Human-readable error message
          example: "Message content is required"
        details:
          type: object
          description: Additional error details
          example:
            field: "message"
            reason: "Field is required"

security:
  - bearerAuth: []
```

## API Implementation Requirements

### Endpoint: POST /api/{user_id}/chat

#### Request Headers
- `Authorization: Bearer {jwt_token}` - Valid JWT token for authentication
- `Content-Type: application/json` - Required for request body

#### Request Body
- `message` (string, required): The user's message to the AI agent
- `conversation_id` (string, optional): UUID of existing conversation to continue
- `metadata` (object, optional): Additional metadata for the message

#### Response Body
- `conversation_id` (string): UUID of the conversation (new or existing)
- `message` (object): The AI agent's response with role and content
- `timestamp` (string): ISO 8601 timestamp of the response
- `next_action` (string): Suggested next action for frontend

#### Error Responses
- `400 Bad Request`: Invalid input parameters
- `401 Unauthorized`: Invalid or missing authentication token
- `500 Internal Server Error`: Unexpected server error

## Authentication & Authorization
- All requests must include a valid JWT token in the Authorization header
- The user_id in the path must match the user ID in the JWT token
- Requests with mismatched user IDs will result in a 401 Unauthorized response

## Rate Limiting
- Per-user rate limiting: 100 requests per minute
- Per-IP rate limiting: 1000 requests per minute

## Validation
- Message content must be between 1 and 1000 characters
- conversation_id must be a valid UUID if provided
- All inputs are sanitized to prevent injection attacks